'use strict';

const Bit_Stream = require( 'bit-buffer' ).BitStream;

const WORDS = [
    "able",
    "also",
    "atom",
    "baby",
    "back",
    "ball",
    "band",
    "bank",
    "base",
    "bell",
    "best",
    "bird",
    "blow",
    "blue",
    "boat",
    "body",
    "bone",
    "book",
    "born",
    "both",
    "burn",
    "busy",
    "call",
    "camp",
    "card",
    "care",
    "case",
    "city",
    "coat",
    "cold",
    "come",
    "cook",
    "cool",
    "copy",
    "corn",
    "cost",
    "crop",
    "dark",
    "deal",
    "dear",
    "deep",
    "done",
    "door",
    "down",
    "draw",
    "drop",
    "duck",
    "east",
    "edge",
    "else",
    "ever",
    "face",
    "fact",
    "fall",
    "farm",
    "fast",
    "feed",
    "feel",
    "feet",
    "fill",
    "find",
    "fire",
    "fish",
    "flat",
    "flow",
    "food",
    "foot",
    "form",
    "free",
    "from",
    "full",
    "game",
    "give",
    "glad",
    "gold",
    "gone",
    "good",
    "grow",
    "hair",
    "hand",
    "hard",
    "have",
    "head",
    "hear",
    "heat",
    "held",
    "here",
    "high",
    "hill",
    "hold",
    "home",
    "hope",
    "huge",
    "hunt",
    "idea",
    "inch",
    "iron",
    "join",
    "jump",
    "just",
    "keep",
    "kind",
    "know",
    "lake",
    "land",
    "last",
    "late",
    "left",
    "life",
    "lift",
    "like",
    "line",
    "list",
    "long",
    "look",
    "lost",
    "loud",
    "love",
    "made",
    "main",
    "make",
    "many",
    "mark",
    "mass",
    "mean",
    "mile",
    "milk",
    "miss",
    "moon",
    "more",
    "most",
    "move",
    "must",
    "name",
    "near",
    "neck",
    "need",
    "noon",
    "nose",
    "note",
    "only",
    "open",
    "over",
    "page",
    "pair",
    "part",
    "path",
    "pick",
    "plan",
    "play",
    "port",
    "post",
    "pull",
    "push",
    "race",
    "rail",
    "rain",
    "real",
    "rest",
    "ride",
    "ring",
    "road",
    "rock",
    "roll",
    "room",
    "rope",
    "rose",
    "rule",
    "safe",
    "salt",
    "same",
    "save",
    "seed",
    "sell",
    "sent",
    "ship",
    "shoe",
    "shop",
    "show",
    "side",
    "sing",
    "size",
    "skin",
    "slow",
    "snow",
    "soft",
    "soil",
    "some",
    "song",
    "soon",
    "spot",
    "star",
    "stay",
    "step",
    "such",
    "suit",
    "sure",
    "swim",
    "tail",
    "take",
    "talk",
    "tall",
    "team",
    "tell",
    "term",
    "test",
    "that",
    "them",
    "they",
    "thin",
    "this",
    "thus",
    "time",
    "tiny",
    "tire",
    "told",
    "tone",
    "took",
    "tool",
    "town",
    "tree",
    "trip",
    "true",
    "tube",
    "turn",
    "type",
    "unit",
    "verb",
    "very",
    "wait",
    "walk",
    "wall",
    "want",
    "warm",
    "wash",
    "wave",
    "wear",
    "week",
    "well",
    "went",
    "west",
    "wide",
    "wife",
    "wild",
    "will",
    "wind",
    "wing",
    "wire",
    "wish",
    "with",
    "wood",
    "word",
    "work",
    "yard",
    "year",
    "your"
];

const ENCODING_BLOCK_SIZE = 8;

module.exports = {
    encode: function( input ) {
        const bit_stream = new Bit_Stream( Buffer.isBuffer( input ) ? input : Buffer.from( input ) );
        const encoded = [];

        while ( bit_stream.bitsLeft > 0 ) {
            const raw_value = bit_stream.readBits( Math.min( ENCODING_BLOCK_SIZE, bit_stream.bitsLeft ), false );
            const encoded_value = WORDS[ raw_value ];
            if ( !encoded_value ) {
                throw new Error( `Could not encode value: ${ raw_value }` );
            }
            encoded.push( encoded_value );
        }

        return encoded;
    },

    decode: function( input ) {
        const decoded_stream = new Bit_Stream( Buffer.alloc( Math.ceil( ( input.length * ENCODING_BLOCK_SIZE ) / 8 ) ) );

        input.forEach( word => {
            const index = WORDS.indexOf( word );
            if ( index === -1 ) {
                throw new Error( `Invalid word: ${ word }` );
            }
            decoded_stream.writeBits( index, ENCODING_BLOCK_SIZE );
        } );

        return decoded_stream.view.buffer;
    }
}

// const WORDS = [
//     'about',
//     'above',
//     'abuse',
//     'actor',
//     'added',
//     'admit',
//     'adult',
//     'after',
//     'again',
//     'agent',
//     'agree',
//     'ahead',
//     'aimed',
//     'alarm',
//     'album',
//     'alert',
//     'alias',
//     'alien',
//     'alive',
//     'allow',
//     'alone',
//     'amber',
//     'among',
//     'anger',
//     'angle',
//     'angry',
//     'annex',
//     'apart',
//     'apple',
//     'apply',
//     'april',
//     'areas',
//     'arena',
//     'argue',
//     'arise',
//     'armed',
//     'armor',
//     'array',
//     'arrow',
//     'aside',
//     'asked',
//     'asset',
//     'atlas',
//     'audio',
//     'audit',
//     'autos',
//     'avoid',
//     'award',
//     'aware',
//     'awful',
//     'bacon',
//     'badge',
//     'badly',
//     'baker',
//     'bands',
//     'banks',
//     'based',
//     'basic',
//     'basin',
//     'basis',
//     'batch',
//     'baths',
//     'beach',
//     'beads',
//     'beans',
//     'bears',
//     'beast',
//     'beats',
//     'began',
//     'begin',
//     'begun',
//     'being',
//     'belly',
//     'below',
//     'belts',
//     'bench',
//     'berry',
//     'bikes',
//     'bills',
//     'bingo',
//     'birds',
//     'birth',
//     'black',
//     'blade',
//     'blame',
//     'blank',
//     'blast',
//     'blend',
//     'bless',
//     'blind',
//     'blink',
//     'block',
//     'blond',
//     'blood',
//     'bloom',
//     'blues',
//     'board',
//     'boats',
//     'bonds',
//     'bones',
//     'bonus',
//     'books',
//     'boost',
//     'booth',
//     'boots',
//     'booty',
//     'bored',
//     'bound',
//     'boxed',
//     'brain',
//     'brake',
//     'brand',
//     'brass',
//     'brave',
//     'bread',
//     'break',
//     'breed',
//     'brick',
//     'bride',
//     'bring',
//     'broad',
//     'broke',
//     'brook',
//     'brown',
//     'brush',
//     'bucks',
//     'buddy',
//     'build',
//     'built',
//     'bunch',
//     'bunny',
//     'burns',
//     'burst',
//     'buses',
//     'buyer',
//     'cabin',
//     'cable',
//     'cakes',
//     'calls',
//     'camel',
//     'camps',
//     'canal',
//     'candy',
//     'canon',
//     'cards',
//     'cargo',
//     'carry',
//     'cases',
//     'catch',
//     'cause',
//     'cedar',
//     'cells',
//     'cents',
//     'chain',
//     'chair',
//     'chaos',
//     'charm',
//     'chart',
//     'chase',
//     'cheap',
//     'cheat',
//     'check',
//     'chest',
//     'child',
//     'china',
//     'chips',
//     'chose',
//     'civic',
//     'civil',
//     'claim',
//     'class',
//     'clean',
//     'clear',
//     'clerk',
//     'click',
//     'cliff',
//     'climb',
//     'clips',
//     'clock',
//     'clone',
//     'close',
//     'cloth',
//     'cloud',
//     'clubs',
//     'coach',
//     'coast',
//     'codes',
//     'coins',
//     'color',
//     'combo',
//     'comes',
//     'comic',
//     'condo',
//     'congo',
//     'coral',
//     'costs',
//     'could',
//     'count',
//     'court',
//     'cover',
//     'crack',
//     'craft',
//     'craps',
//     'crash',
//     'crazy',
//     'cream',
//     'creek',
//     'crest',
//     'crime',
//     'crops',
//     'cross',
//     'crowd',
//     'crown',
//     'crude',
//     'cubic',
//     'curve',
//     'cyber',
//     'cycle',
//     'daddy',
//     'daily',
//     'dairy',
//     'daisy',
//     'dance',
//     'dated',
//     'dates',
//     'deals',
//     'dealt',
//     'death',
//     'debug',
//     'decor',
//     'delay',
//     'delta',
//     'dense',
//     'depot',
//     'depth',
//     'derby',
//     'devil',
//     'diary',
//     'digit',
//     'dirty',
//     'disco',
//     'disks',
//     'dodge',
//     'doing',
//     'dolls',
//     'donor',
//     'doors',
//     'doubt',
//     'dover',
//     'dozen',
//     'draft',
//     'drain',
//     'drama',
//     'drawn',
//     'draws',
//     'dream',
//     'dress',
//     'dried',
//     'drill',
//     'drink',
//     'drive',
//     'drops',
//     'drove',
//     'drugs',
//     'drums',
//     'drunk',
//     'dryer',
//     'dutch',
//     'dying',
//     'eagle',
//     'early',
//     'earth',
//     'ebony',
//     'edges',
//     'eight',
//     'elder',
//     'elect',
//     'elite',
//     'email',
//     'empty',
//     'ended',
//     'enemy',
//     'enjoy',
//     'enter',
//     'entry',
//     'equal',
//     'error',
//     'essay',
//     'event',
//     'every',
//     'exact',
//     'exams',
//     'exist',
//     'extra',
//     'faced',
//     'facts',
//     'fails',
//     'fairy',
//     'faith',
//     'false',
//     'fancy',
//     'fares',
//     'farms',
//     'fatal',
//     'fatty',
//     'fault',
//     'favor',
//     'fears',
//     'feeds',
//     'feels',
//     'fence',
//     'ferry',
//     'fever',
//     'fewer',
//     'fiber',
//     'field',
//     'fifth',
//     'fifty',
//     'fight',
//     'filed',
//     'files',
//     'films',
//     'final',
//     'finds',
//     'fired',
//     'firms',
//     'first',
//     'fixed',
//     'flags',
//     'flame',
//     'flash',
//     'fleet',
//     'flesh',
//     'float',
//     'flood',
//     'floor',
//     'flows',
//     'fluid',
//     'flush',
//     'flyer',
//     'focal',
//     'focus',
//     'folks',
//     'fonts',
//     'foods',
//     'force',
//     'forge',
//     'forms',
//     'forth',
//     'forty',
//     'forum',
//     'found',
//     'frame',
//     'fresh',
//     'front',
//     'frost',
//     'fruit',
//     'fully',
//     'funds',
//     'funky',
//     'funny',
//     'fuzzy',
//     'gains',
//     'games',
//     'gamma',
//     'gates',
//     'ghost',
//     'giant',
//     'gifts',
//     'girls',
//     'given',
//     'gives',
//     'glass',
//     'globe',
//     'glory',
//     'goals',
//     'going',
//     'goods',
//     'grace',
//     'grade',
//     'grain',
//     'grams',
//     'grand',
//     'grant',
//     'graph',
//     'grass',
//     'grave',
//     'great',
//     'greek',
//     'green',
//     'grill',
//     'gross',
//     'group',
//     'grove',
//     'grown',
//     'grows',
//     'guard',
//     'guess',
//     'guest',
//     'guide',
//     'guild',
//     'hairy',
//     'hands',
//     'handy',
//     'happy',
//     'haven',
//     'heads',
//     'heard',
//     'heart',
//     'heavy',
//     'hello',
//     'helps',
//     'highs',
//     'hills',
//     'hints',
//     'hired',
//     'hobby',
//     'holds',
//     'holes',
//     'holly',
//     'homes',
//     'honey',
//     'honor',
//     'hoped',
//     'horse',
//     'hosts',
//     'hotel',
//     'hours',
//     'house',
//     'howto',
//     'human',
//     'humor',
//     'icons',
//     'ideal',
//     'ideas',
//     'image',
//     'inbox',
//     'index',
//     'inner',
//     'input',
//     'inter',
//     'intro',
//     'issue',
//     'items',
//     'ivory',
//     'jeans',
//     'jewel',
//     'joins',
//     'joint',
//     'jokes',
//     'judge',
//     'juice',
//     'karma',
//     'keeps',
//     'kills',
//     'kinda',
//     'kinds',
//     'kings',
//     'kitty',
//     'knife',
//     'knock',
//     'known',
//     'knows',
//     'label',
//     'labor',
//     'laden',
//     'lakes',
//     'lamps',
//     'lands',
//     'lanes',
//     'large',
//     'laser',
//     'later',
//     'latex',
//     'latin',
//     'laugh',
//     'layer',
//     'leads',
//     'learn',
//     'lease',
//     'least',
//     'leave',
//     'legal',
//     'lemon',
//     'level',
//     'light',
//     'liked',
//     'likes',
//     'limit',
//     'lined',
//     'lines',
//     'links',
//     'lions',
//     'lists',
//     'lived',
//     'liver',
//     'loads',
//     'loans',
//     'lobby',
//     'local',
//     'locks',
//     'lodge',
//     'logic',
//     'looks',
//     'loops',
//     'loved',
//     'lover',
//     'lower',
//     'lucky',
//     'lunch',
//     'lying',
//     'lyric',
//     'macro',
//     'magic',
//     'mails',
//     'major',
//     'maker',
//     'makes',
//     'males',
//     'mambo',
//     'manor',
//     'maple',
//     'march',
//     'marks',
//     'marsh',
//     'match',
//     'maybe',
//     'mayor',
//     'meals',
//     'means',
//     'meant',
//     'media',
//     'meets',
//     'menus',
//     'mercy',
//     'merge',
//     'merit',
//     'merry',
//     'metal',
//     'meter',
//     'metro',
//     'micro',
//     'might',
//     'miles',
//     'mills',
//     'mines',
//     'minor',
//     'minus',
//     'mixed',
//     'mixer',
//     'model',
//     'modes',
//     'money',
//     'month',
//     'moral',
//     'motel',
//     'motor',
//     'mount',
//     'mouse',
//     'mouth',
//     'moved',
//     'movie',
//     'multi',
//     'music',
//     'nails',
//     'naked',
//     'named',
//     'nasty',
//     'naval',
//     'needs',
//     'nerve',
//     'never',
//     'newer',
//     'newly',
//     'night',
//     'noble',
//     'nodes',
//     'noise',
//     'north',
//     'noted',
//     'novel',
//     'nurse',
//     'oasis',
//     'occur',
//     'ocean',
//     'offer',
//     'often',
//     'older',
//     'olive',
//     'omega',
//     'onion',
//     'opens',
//     'opera',
//     'orbit',
//     'order',
//     'organ',
//     'other',
//     'outer',
//     'owned',
//     'owner',
//     'oxide',
//     'ozone',
//     'packs',
//     'pages',
//     'paint',
//     'pairs',
//     'panel',
//     'panic',
//     'pants',
//     'paper',
//     'parks',
//     'parts',
//     'party',
//     'pasta',
//     'paste',
//     'patch',
//     'paths',
//     'patio',
//     'peace',
//     'pearl',
//     'peers',
//     'penny',
//     'phase',
//     'phone',
//     'photo',
//     'piano',
//     'picks',
//     'pills',
//     'pilot',
//     'pipes',
//     'pitch',
//     'pixel',
//     'pizza',
//     'place',
//     'plane',
//     'plans',
//     'plant',
//     'plate',
//     'plays',
//     'plaza',
//     'plots',
//     'poems',
//     'point',
//     'poker',
//     'polar',
//     'polls',
//     'pools',
//     'ports',
//     'posts',
//     'pound',
//     'power',
//     'press',
//     'price',
//     'pride',
//     'prime',
//     'print',
//     'prior',
//     'prize',
//     'probe',
//     'promo',
//     'proof',
//     'proud',
//     'prove',
//     'proxy',
//     'pulse',
//     'pumps',
//     'punch',
//     'puppy',
//     'purse',
//     'queen',
//     'query',
//     'quest',
//     'quick',
//     'quilt',
//     'quote',
//     'races',
//     'racks',
//     'radar',
//     'radio',
//     'raise',
//     'rally',
//     'ranch',
//     'range',
//     'ranks',
//     'rapid',
//     'rated',
//     'ratio',
//     'reach',
//     'reads',
//     'ready',
//     'realm',
//     'rebel',
//     'refer',
//     'rehab',
//     'relax',
//     'relay',
//     'remix',
//     'renew',
//     'reply',
//     'reset',
//     'retro',
//     'rider',
//     'rides',
//     'ridge',
//     'right',
//     'rings',
//     'risks',
//     'river',
//     'roads',
//     'robin',
//     'robot',
//     'rocks',
//     'rocky',
//     'roger',
//     'rolls',
//     'roman',
//     'rooms',
//     'roots',
//     'roses',
//     'rough',
//     'round',
//     'rover',
//     'royal',
//     'rugby',
//     'ruled',
//     'rural',
//     'safer',
//     'saint',
//     'salad',
//     'sales',
//     'salon',
//     'samba',
//     'sandy',
//     'satin',
//     'sauce',
//     'saved',
//     'saver',
//     'scale',
//     'scary',
//     'scene',
//     'scoop',
//     'scope',
//     'score',
//     'scout',
//     'screw',
//     'scuba',
//     'seats',
//     'seeds',
//     'seeks',
//     'seems',
//     'sells',
//     'sends',
//     'sense',
//     'serum',
//     'serve',
//     'setup',
//     'seven',
//     'shade',
//     'shaft',
//     'shake',
//     'shall',
//     'shame',
//     'shape',
//     'share',
//     'shark',
//     'sharp',
//     'sheep',
//     'sheer',
//     'sheet',
//     'shelf',
//     'shell',
//     'shift',
//     'shine',
//     'ships',
//     'shirt',
//     'shock',
//     'shoes',
//     'shoot',
//     'shops',
//     'shore',
//     'short',
//     'shots',
//     'shown',
//     'shows',
//     'sides',
//     'sight',
//     'sigma',
//     'signs',
//     'silly',
//     'since',
//     'sites',
//     'sixth',
//     'sized',
//     'skill',
//     'skins',
//     'skirt',
//     'sleep',
//     'slide',
//     'slope',
//     'slots',
//     'small',
//     'smart',
//     'smell',
//     'smile',
//     'smith',
//     'smoke',
//     'snake',
//     'socks',
//     'solar',
//     'solid',
//     'solve',
//     'songs',
//     'sonic',
//     'sorry',
//     'sorts',
//     'souls',
//     'sound',
//     'south',
//     'space',
//     'spare',
//     'speak',
//     'speed',
//     'spell',
//     'spend',
//     'spice',
//     'spine',
//     'split',
//     'spoke',
//     'sport',
//     'spots',
//     'spray',
//     'squad',
//     'stack',
//     'staff',
//     'stage',
//     'stake',
//     'stamp',
//     'stand',
//     'stars',
//     'start',
//     'state',
//     'stays',
//     'steal',
//     'steam',
//     'steel',
//     'steps',
//     'stick',
//     'still',
//     'stock',
//     'stone',
//     'stood',
//     'stops',
//     'store',
//     'storm',
//     'story',
//     'strap',
//     'strip',
//     'stuck',
//     'study',
//     'stuff',
//     'style',
//     'sugar',
//     'suits',
//     'sunny',
//     'super',
//     'surge',
//     'sweet',
//     'swift',
//     'swing',
//     'swiss',
//     'sword',
//     'table',
//     'taken',
//     'takes',
//     'tales',
//     'talks',
//     'tanks',
//     'tapes',
//     'tasks',
//     'taste',
//     'taxes',
//     'teach',
//     'teams',
//     'tears',
//     'teddy',
//     'teens',
//     'teeth',
//     'tells',
//     'terms',
//     'tests',
//     'thank',
//     'theft',
//     'theme',
//     'there',
//     'these',
//     'theta',
//     'thick',
//     'thing',
//     'think',
//     'third',
//     'those',
//     'three',
//     'throw',
//     'tiger',
//     'tight',
//     'tiles',
//     'timed',
//     'timer',
//     'tired',
//     'title',
//     'today',
//     'token',
//     'toner',
//     'tools',
//     'tooth',
//     'topic',
//     'total',
//     'touch',
//     'tours',
//     'tower',
//     'towns',
//     'toxic',
//     'trace',
//     'track',
//     'trade',
//     'trail',
//     'train',
//     'trash',
//     'trees',
//     'trend',
//     'trial',
//     'tribe',
//     'trick',
//     'tried',
//     'trips',
//     'trout',
//     'truck',
//     'truly',
//     'trunk',
//     'trust',
//     'truth',
//     'tubes',
//     'tuner',
//     'turbo',
//     'turns',
//     'twice',
//     'twins',
//     'twist',
//     'types',
//     'ultra',
//     'uncle',
//     'under',
//     'union',
//     'units',
//     'unity',
//     'until',
//     'upper',
//     'upset',
//     'urban',
//     'usage',
//     'users',
//     'using',
//     'usual',
//     'valid',
//     'value',
//     'vault',
//     'venue',
//     'verse',
//     'video',
//     'views',
//     'villa',
//     'virus',
//     'visit',
//     'vista',
//     'vital',
//     'vocal',
//     'voice',
//     'voted',
//     'wages',
//     'wagon',
//     'walks',
//     'walls',
//     'wants',
//     'waste',
//     'watch',
//     'water',
//     'watts',
//     'waves',
//     'weeks',
//     'weird',
//     'whale',
//     'wheat',
//     'wheel',
//     'where',
//     'while',
//     'white',
//     'wider',
//     'width',
//     'winds',
//     'wines',
//     'wings',
//     'wired',
//     'witch',
//     'woman',
//     'woods',
//     'words',
//     'works',
//     'world',
//     'worry',
//     'worse',
//     'worst',
//     'worth',
//     'would',
//     'wound',
//     'wrist',
//     'write',
//     'wrong',
//     'wrote',
//     'yards',
//     'years',
//     'young',
//     'yours',
//     'youth',
//     'zones'
// ];

// const ENCODING_BLOCK_SIZE = 10; // number of bits we can address with our word list